config/routes.rb
Rails.application.routes.draw do
  

  resources :company_goals
  resources :goals
  resources :snippets
  devise_for :users
  resources :users
  resources :posts do 
  	resources :reviews
  end

  root 'company_goals#index'

end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :website

	has_many :posts
	has_many :reviews
	has_many :snippets
	has_many :goals

	has_attached_file :profile,
    	style: {
      		:large =>"500x500>",
      		:medium => "300x300>",
      		:thumb => "100x100>" },
		:url  => "/assets/images/users/:id/:style/:basename.:extension",
		:path => "rails_root/public/assets/images/:id/:style/:basename.:extension"
  
  	validates_attachment :profile, 
      	content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
	@posts = @user.posts.order("created_at DESC")
	@snippets = @user.snippets.order("created_at DESC")
	@goals = @user.goals.order("created_at DESC")
  end
  
end

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<h1><%= @user.name %></h1>
<h4><%= @user.email %></h4>

<% if user_signed_in? && @user.id == current_user.id %>
		<p><%= link_to 'Edit Profile',edit_user_registration_path %></p>
<% end %>
<div class="col-md-6 col-sm-offset-3">
	<div class="snippet-index-desc">
		<div class="snippet-index-content">
			<h6>Snippet:</h6>
			 <% @snippets.each do |snippet| %>
				<p><%= markdown(snippet.summary) %></p>
				<div class="new-btn">
				<p>	
					<%= link_to "Edit", edit_snippet_path(id: snippet.id), :class => 'waves-effect btn-large' %>
				</p>
				</div>
				
		 	<% end %>
		</div>

	</div>	
	<% if @user.snippets.count == 0 %>
	<div class="new-btn">
		<%= link_to "Create Snippet", new_snippet_path,  :class => 'waves-effect btn-large' %>

	</div>
	<% end %>
</div>
</div>
<h1 class="current-category"><%= params[:type] %></h1>


<div class="row">
	<div class="col-md-8">
	<% if @posts.count == 0 %>
		<h1>This user has no posts.</h1>
		<% else %>

			<h2>Posts</h2>
			<% @posts.each do |post| %>
				
				<div class="book-index-desc">
					<div class="book-index-content">
						<h4><%= link_to post.title, post %></h4>
						<h6><%= post.summary %></h6>
						<h6>Submitted <%= time_ago_in_words(post.created_at) %> ago, by <%= link_to post.user.name, user_path(id: post.user.id) %> in
						<%= link_to post.type.name, posts_path(type: post.type.name), class: "link" %></h6>

					</div>
				</div>
			<% end %>

	<% end %>	
	</div>	
	
	<div class="col-md-4">
	<h2>OKR's</h2>
	<h4>Current OKR's</h4>
		<% if @user.goals.where(complete: false).count >= 1 %>
		
			<% @goals.each do |goal| %>
				<% if goal.complete == false %>
					<div class="goal-index-desc">
						<div class="goal-index-content">
				 	
				 			<div class="okr-index-container">
								<h6 class="goal-header">Objective:</h6>
								<p><%= goal.objecive %></p>
								<h6 class="goal-header">Key Results:</h6>
								<p><%= markdown(goal.key_results) %></p>
								<h6 class="goal-header">Deadline:</h6>
								<p><%= goal.deadline.strftime("%d %B %Y") %></p>
							</div>
							<% if current_user.id == goal.user.id %>
								<div class="edit-goal-index-button">
									<%= link_to "EDIT", edit_goal_path(id: goal.id) %>
								</div>
								<div class="complete-goal-index-button">
									<%= link_to "Completed", goal_path(:id => goal.id, "goal[complete]" => true), :remote => true, :method => :patch, 
	:data => {:confirm => "Nice work, #{current_user.name}. Can you confirm you've completeted:\n\n#{goal.objecive}"} %>

								</div>
							<% end %>
			 	
			 	
						</div>
		
					</div>	
				<% end %>
			<% end %>
		<% else %>
			<p>There are no OKR's</p>	
		<% end %> 	
	
		<div class="new-btn">
			<%= link_to "New OKR", new_goal_path,  :class => 'waves-effect btn-large' %>
		</div>
		
		<% if @user.goals.where(complete: true).count >= 1 %>

		<h4>Past OKR's</h4>
			<% @goals.each do |goal| %>
				<% if goal.complete %>
					<div class="goal-index-desc">
						<div class="goal-index-content">
				 	
				 			<div class="okr-index-container">
								<h6 class="goal-header">Objective:</h6>
								<p><%= goal.objecive %></p>
								<h6 class="goal-header">Key Results:</h6>
								<p><%= markdown(goal.key_results) %></p>
								<h6 class="goal-header">Deadline:</h6>
								<p><%= goal.deadline.strftime("%d %B %Y") %></p>
							</div>
							<% if current_user.id == goal.user.id %>
								<div class="edit-goal-index-button">
									<%= link_to "Not Completed", goal_path(:id => goal.id, "goal[complete]" => false), :remote => true, :method => :patch, :data => {:confirm => 'Are you sure you want to mark this OKR as incomplete?'}  %>

								</div>
			 				<% end %>
			 	
						</div>
		
					</div>	
				<% end %>
			<% end %>
		<% else %>

		<% end %>	

	</div>



</div>