config/routes.rb
Rails.application.routes.draw do
  

  resources :company_goals
  resources :goals
  resources :snippets
  devise_for :users
  resources :users
  resources :posts do 
  	resources :reviews
  end

  root 'company_goals#index'

end

app/models/company_goal.rb
class CompanyGoal < ApplicationRecord
end

app/controllers/company_goals_controller.rb
 #    COMPANY GOALS SCHEMA
 #    t.string   "objective"
 #    t.text     "key_results"
 #    t.date     "deadline"
 #    t.boolean  "complete"
 #    t.datetime "created_at",  null: false
 #    t.datetime "updated_at",  null: false

# This class is responsible for managing company goals (in the form of OKR's).

class CompanyGoalsController < ApplicationController
  before_action :set_company_goal, only: [:show, :edit, :update, :destroy]

  def index
    @company_goals = CompanyGoal.all
    @goals = Goal.all.order("created_at DESC")
    @users = User.all.order("created_at DESC")
  end

  def show
  end

  def new
    @company_goal = CompanyGoal.new
  end

  def edit
  end

  def create
    @company_goal = CompanyGoal.new(company_goal_params)

    respond_to do |format|
      if @company_goal.save
        format.html { redirect_to company_goals_path, notice: 'Company goal was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @company_goal.update(company_goal_params)
        format.html { redirect_to company_goals_path, notice: 'Company goal was successfully created.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @company_goal.destroy
    respond_to do |format|
      format.html { redirect_to company_goals_url, notice: 'Company goal was successfully destroyed.' }
    end
  end

  private
    
    def set_company_goal
      @company_goal = CompanyGoal.find(params[:id])
    end

    
    def company_goal_params
      params.require(:company_goal).permit(:objective, :key_results, :deadline, :complete)
    end
end

app/views/company_goals/_form.html.erb
<%= simple_form_for(@company_goal) do |f| %>
  <%= f.error_notification %>

  <div class="form-material">
    <%= f.input :objective,  label: false, placeholder: "Objective" %>
    <%= f.input :key_results, label: false, placeholder: "Key Results" %>
    <%= f.input :deadline %>
    <%= f.input :complete %>
  </div>

  <div class="form-actions">
    <div class="new-btn">
      <%= f.button :submit, :class => 'waves-effect btn-large' %>
    </div>
  </div>
<% end %>

app/views/company_goals/edit.html.erb
<h1>Edit Company OKR</h1>

<%= render 'form', company_goal: @company_goal %>

<div class="links btn-group">
	<%= link_to "Back", company_goals_path, class: "btn btn-custom" %>
</div>

app/views/company_goals/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<div class="row">
  <div class="col-md-9">
    <h1>Company OKR's</h1>
  </div>
  <div class="col-md-3">
    <div class="new-btn">
      <%= link_to 'New Company Goal', new_company_goal_path, :class => 'waves-effect btn-large' %>
    </div>
  </div>
</div>

<div class="row">
  <% @company_goals.each do |company_goal| %>
    <% if company_goal.complete == false %>
      <div class="col-md-4">
        <div class="goal-index-desc">
          <div class="goal-index-content">
            <div class="okr-index-container">
              <h6 class="goal-header">Objective:</h6>
              <h4><%= company_goal.objective %></h4>
              <br>
              <h6 class="goal-header">Key Results:</h6>
              <p><%= markdown(company_goal.key_results) %></p>
              <h6 class="goal-header">Deadline:</h6>
              <p><%= company_goal.deadline.strftime("%d %B %Y") %></p> 
            </div>
          </div>
                 
          <div class="edit-goal-index-button">
            <%= link_to "EDIT", edit_company_goal_path(id: company_goal.id) %>
          </div>
          <div class="complete-goal-index-button">
            <%= link_to "Completed", company_goal_path(:id => company_goal.id, "company_goal[complete]" => true), :remote => true, :method => :patch %>
          </div>
        </div>   
      </div>  
    <% end %>    
  <% end %>
</div>

<hr>

<div class="row">
  <% @company_goals.each do |company_goal| %>
    <% if company_goal.complete == true %>
    <h4>Past OKR's</h4>
      <div class="col-md-4">
        <div class="goal-index-desc">
          <div class="goal-index-content">
            <div class="okr-index-container">
              <h6 class="goal-header">Objective:</h6>
              <p><%= company_goal.objective %></p>
              <h6 class="goal-header">Key Results:</h6>
              <p><%= markdown(company_goal.key_results) %></p>
              <h6 class="goal-header">Deadline:</h6>
              <p><%= company_goal.deadline.strftime("%d %B %Y") %></p> 
            </div>
          </div>
                 
          <div class="edit-goal-index-button">
            <%= link_to "Not Completed", company_goal_path(:id => company_goal.id, "company_goal[complete]" => false), :remote => true, :method => :patch, :data => {:confirm => 'Are you sure you want to mark this OKR as incomplete?'}  %>

          </div>
        </div>   
      </div>  
    <% end %>    
  <% end %>
</div>
<% end %>

app/views/company_goals/new.html.erb
<h1>New Company OKR</h1>

<%= render 'form', company_goal: @company_goal %>

<%= link_to 'Back', company_goals_path %>

app/views/company_goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Objective:</strong>
  <%= @company_goal.objective %>
</p>

<p>
  <strong>Key results:</strong>
  <%= @company_goal.key_results %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @company_goal.deadline %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @company_goal.complete %>
</p>

<%= link_to 'Edit', edit_company_goal_path(@company_goal) %> |
<%= link_to 'Back', company_goals_path %>