config/routes.rb
Rails.application.routes.draw do
  

  resources :company_goals
  resources :goals
  resources :snippets
  devise_for :users
  resources :users
  resources :posts do 
  	resources :reviews
  end

  root 'company_goals#index'

end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	belongs_to :type
	has_many :reviews

  has_attached_file :post_img, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :post_img, content_type: /\Aimage\/.*\z/

	module UrlHelper
 		def url_with_protocol(url)
  			/^http/i.match(url) ? url : "http://#{url}"
 		end
	end

end

app/controllers/posts_controller.rb
# POSTS SCHEMA:
    # t.string   "title"
    # t.string   "summary"
    # t.text     "description"
    # t.string   "author"
    # t.datetime "created_at",            null: false
    # t.datetime "updated_at",            null: false
    # t.integer  "user_id"
    # t.integer  "category_id"
    # t.integer  "type_id"
    # t.string   "post_img_file_name"
    # t.string   "post_img_content_type"
    # t.integer  "post_img_file_size"
    # t.datetime "post_img_updated_at"
    # t.string   "url"

# TODO: Set up paperclip gem

class PostsController < ApplicationController
	
	before_action :find_book, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:new, :edit]

	def index
		if params[:type].blank?
			@posts = Post.all.order("created_at DESC")
		else
			# Sets post cateogory 
			@type_id = Type.find_by(name: params[:type]).id
			@posts = Post.where(:type_id => @type_id).order("created_at DESC")
		end
	end

	def new
		@post = current_user.posts.build
		@types = Type.all.map{ |c| [c.name, c.id]}
	end

	def show
	end

	# TODO: Saniize URL's (see line 77)
	def create
		@post = current_user.posts.build(post_params)
		@post.type_id = params[:type_id]
		@types = Type.all.map{ |c| [c.name, c.id] }		
		if @post.save
			redirect_to posts_path
			flash[:success] = "Post successfully created"
		else
			render 'new'
		end
	end

	def edit
		@types = Type.all.map{ |c| [c.name, c.id] }
	end

	def update
		@post.type_id = params[:type_id]
		@types = Type.all.map{ |c| [c.name, c.id] }
		if @post.update(post_params)
			redirect_to post_path(@post)
			flash[:notice] = "Post successfully updated"
		else
			render 'edit'
		end 

	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

  	def url_with_protocol(url)
		    /^http/i.match(url) ? url : "http://#{url}"
 	end


	private

		def post_params
			params.require(:post).permit(:title, :summary, :description, :author, :type_id ,:post_img, :url)
		end

		def find_book
			@post = Post.find(params[:id])
		end


end

app/views/posts/_form.html.erb
<%= simple_form_for @post, :html => { :multipart => true } do |f| %>

<%= select_tag(:type_id, options_for_select(@types), :prompt => "Select a type") %>
<div class="form-material">
	<%= f.input :title, label: false, placeholder: "Post Title" %>
	<%= f.input :summary, label: false, placeholder: "Summary" %>
	<%= f.input :url, label: false, placeholder: "Link" %>
	<%= f.input :description, label: "Post:" %>
	<%= f.input :author, label: false, placeholder: "Author" %>
</div>	

	<div class="new-btn">
		<%= f.button :submit, :class => 'waves-effect btn-large' %>
	</div>

<% end %>

<script>
var simplemde = new SimpleMDE();
</script>

app/views/posts/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<div class="new-book-form">

		<h1>Edit Post</h1>

		<%= simple_form_for @post, :html => { :multipart => true } do |f| %>
			
			<%= f.select :type_id, @types %>
			<%= f.file_field :post_img %>
			<%= f.input :title, label: "Post Title" %>
			<%= f.input :summary, label: "Summary" %>
			<%= f.input :url, label: "Link" %>
			<%= f.input :description %>
			<%= f.input :author %>
			<div class="new-btn">
				<%= f.button :submit, :class => 'waves-effect btn-large' %>
			</div>


		<% end %>
	</div>
</div>	

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<div class="row">

	<div class="col-md-9">
		<h1 class="current-category">Posts: <strong><%= params[:type] %></strong></h1>

		<% if @posts.count == 0 %>
			<h1>There are no posts in this category</h1>
			<% else %>

			

				<% @posts.each do |post| %>

					<div class="col-md-12">
						
						<div class="book-index-desc">
							<div class="book-index-content">
								<h4><%= link_to post.title, post %></h4>
								<h6><%= post.summary %></h6>
								<h6>Submitted <%= time_ago_in_words(post.created_at) %> ago, by <%= link_to post.user.name, user_path(id: post.user.id) %> in
								<%= link_to post.type.name, posts_path(type: post.type.name), class: "link" %></h6>

							</div>
						</div>

					</div>	
				<% end %>
		<% end %>
	</div>	

	<div class="col-md-3">
		<% if user_signed_in? %>
		   	<div class="new-btn">
		   		<p><%= link_to "New Post", new_post_path, class: "waves-effect btn-large" %></p>
			</div>
		    <li class="dropdown">
		        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" area-expanded="false">Categories <span class="caret"></span></a>
		        <ul class="dropdown-menu" role="menu">
		            <% Type.all.each do |type| %>
		              <li class="<%= 'active' if params[:type] == type.name %>">
		                <%= link_to type.name, posts_path(type: type.name), class: "link" %>
		              </li>
		            <% end %>
		        </ul>
		    </li>
		<% end %> 
	</div>	
	
</div>
<% end %>

app/views/posts/new.html.erb
<div class="cod-md-6 col-md-offset-3">

	<div class="new-book-form">
		<h1>New Post </h1>

		<%= render 'form' %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="post-info">
			<h2 class="post-title"><%= @post.title %></h2>
			<h6>Submitted <%= time_ago_in_words(@post.created_at) %> ago, by <%= link_to @post.user.name, user_path(id: @post.user.id) %> in <%= link_to @post.type.name, posts_path(type: @post.type.name), class: "link" %></h6>
			<h6 ><span>Author: </span><%= @post.author %></h6>



			<h6>Link: <%= @post.url %></h6>
			<div class="post-desc">
				<p><%= markdown(@post.description) %></p>
			</div>
<div class="links btn-group">
				<%= link_to "Back", root_path, class: "btn btn-custom" %>

					<% if user_signed_in? %>
						<% if @post.user_id == current_user.id %>
							<%= link_to "Edit", edit_post_path(@post), class: "btn btn-custom" %>
							<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>
						<% end %>
					<% end %>
			</div>	

		</div>
	<div class="col-md-8">
		<div class="reviews">
			<h1>Notes</h1>
			<%= render @post.reviews %>
			<div class="new-btn">
				<%= link_to "Add Note", new_post_review_path(@post), class: "waves-effect btn-large" %> 
				<br>
				<br>
			</div>
	</div>		
				
		</div>
	</div>

</div>