config/routes.rb
Rails.application.routes.draw do
  

  resources :company_goals
  resources :goals
  resources :snippets
  devise_for :users
  resources :users
  resources :posts do 
  	resources :reviews
  end

  root 'company_goals#index'

end

app/models/goal.rb
class Goal < ApplicationRecord
	belongs_to :user
end

app/controllers/goals_controller.rb
# GOALS SCHEMA
    # t.string   "objecive"
    # t.text     "key_results"
    # t.date     "deadline"
    # t.datetime "created_at",  null: false
    # t.datetime "updated_at",  null: false
    # t.integer  "user_id"
    # t.boolean  "complete"

# This class is responsible for managing user goals (in the form of OKR's). 

class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]


  def index
    @goals = Goal.all.order("created_at DESC")
  end


  def show
  end

  
  def new
    @goal = current_user.goals.build
  end


  def edit
  end

  
  def create
    @goal = current_user.goals.build(goal_params)

    respond_to do |format|
      if @goal.save
        format.html { redirect_to user_path(@goal.user.id), notice: 'Goal was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to user_path(@goal.user.id), notice: 'Goal was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to goals_url, notice: 'Goal was successfully destroyed.' }
    end
  end

  private
    
    def set_goal
      @goal = Goal.find(params[:id])
    end

    def goal_params
      params.require(:goal).permit(:objecive, :key_results, :deadline, :complete)
    end
end

app/views/goals/_form.html.erb
<%= simple_form_for(@goal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs form-material">
    <%= f.input :objecive, label: false, placeholder: "Objecive" %>
    <%= f.input :key_results, label: false, placeholder: "Key Results" %>
    <%= f.input :deadline %>
	<%= f.input :complete, as: :boolean, checked_value: true, unchecked_value: false %>

  </div>

  <div class="form-actions new-btn">
    <%= f.button :submit, :class => 'waves-effect btn-large' %>
  </div>
<% end %>

app/views/goals/edit.html.erb
<h1>Edit OKR</h1>

	<%= render 'form', goal: @goal %>


<%= link_to 'Show', @goal %> |
<%= link_to 'Back', user_path(current_user) %>

app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goals</h1>

<table>
  <thead>
    <tr>
      <th>Objecive</th>
      <th>Key results</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goals.each do |goal| %>
      <tr>
        <td><%= goal.objecive %></td>
        <td><%= goal.key_results %></td>
        <td><%= goal.deadline %></td>
        <td><%= link_to 'Show', goal %></td>
        <td><%= link_to 'Edit', edit_goal_path(goal) %></td>
        <td><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Goal', new_goal_path %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<%= render 'form', goal: @goal %>

<%= link_to 'Back', user_path(current_user) %>

app/views/goals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Objecive:</strong>
  <%= @goal.objecive %>
</p>

<p>
  <strong>Key results:</strong>
  <%= @goal.key_results %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @goal.deadline %>
</p>

<%= link_to 'Edit', edit_goal_path(@goal) %> |
<%= link_to 'Back', goals_path %>